# Generated by Django 5.0.4 on 2024-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="onAds",
            field=models.BooleanField(default=False),
        ),
    ]
