# Generated by Django 5.0.4 on 2024-04-22 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_rename_type_portfolio_residenttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="size",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
