# Generated by Django 5.0.4 on 2024-04-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolioimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='address',
            new_name='portfolioaddress',
        ),
    ]
