# Generated by Django 5.0.4 on 2024-04-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiorcompany', '0002_interiorcompany_image'),
        ('portfolio', '0007_rename_address_portfolio_portfolioaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='interiorCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interiorcompany.interiorcompany'),
        ),
    ]
