# Generated by Django 5.0.4 on 2024-04-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_interiorcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolioaddress',
            new_name='address',
        ),
    ]
