# Generated by Django 5.0.4 on 2024-04-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_resume_userprofile_bankbook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='useraddress',
        ),
    ]
