# Generated by Django 5.0.4 on 2024-04-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_address_userprofile_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='useraddress',
            new_name='address',
        ),
    ]
