# Generated by Django 5.0.4 on 2024-04-23 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('contents', models.TextField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('interiorCompany', models.CharField(max_length=100, null=True)),
                ('residentType', models.CharField(choices=[('오피스텔', 'Opistel'), ('아파트', 'Apartment'), ('빌라', 'Villa')], max_length=20, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('size', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('likeCount', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)])),
                ('onAds', models.BooleanField(default=False)),
            ],
        ),
    ]
