# Generated by Django 5.0.4 on 2024-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='intimacyRating',
            field=models.CharField(choices=[('아쉬워요', '아쉬워요'), ('보통이에요', '보통이에요'), ('최고에요', '최고에요')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='priceRating',
            field=models.CharField(choices=[('아쉬워요', '아쉬워요'), ('보통이에요', '보통이에요'), ('최고에요', '최고에요')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='qualityRating',
            field=models.CharField(choices=[('아쉬워요', '아쉬워요'), ('보통이에요', '보통이에요'), ('최고에요', '최고에요')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='totalRating',
            field=models.CharField(choices=[('오피스텔', 'Opistel'), ('아파트', 'Apartment'), ('빌라', 'Villa')], max_length=20, null=True),
        ),
    ]
