# Generated by Django 5.0.4 on 2024-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0003_customerreviewimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreviewimage',
            old_name='portfolio',
            new_name='review',
        ),
    ]
