# Generated by Django 5.0.4 on 2024-05-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0003_alter_customerreview_totalrating'),
        ('interiorcompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='interiorCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interiorcompany.interiorcompany'),
        ),
    ]
