# Generated by Django 5.0.4 on 2024-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0004_alter_customerreview_interiorcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='interiorCompany',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
