# Generated by Django 5.0.4 on 2024-04-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0004_rename_portfolio_customerreviewimage_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='address',
            new_name='reviewaddress',
        ),
    ]
