# Generated by Django 5.0.4 on 2024-04-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerreview', '0005_rename_address_customerreview_reviewaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='reviewaddress',
            new_name='address',
        ),
    ]
