# Generated by Django 5.0.4 on 2024-05-01 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woodworking', models.CharField(max_length=50)),
                ('woodworkingCount', models.IntegerField()),
                ('wallpapering', models.CharField(max_length=50)),
                ('wallpaperingCount', models.IntegerField()),
                ('floor', models.CharField(max_length=50)),
                ('floorCount', models.IntegerField()),
                ('bathroom', models.CharField(max_length=50)),
                ('bathroomCount', models.IntegerField()),
                ('sink', models.CharField(max_length=50)),
                ('sinkCount', models.IntegerField()),
                ('demolition', models.CharField(max_length=50)),
                ('demolitionCount', models.IntegerField()),
                ('basic', models.CharField(max_length=50)),
                ('basicCount', models.IntegerField()),
                ('buildingType', models.CharField(max_length=50)),
                ('interiordate', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('remainaddress', models.CharField(max_length=150)),
                ('customername', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('prefertime', models.CharField(max_length=50)),
                ('promotioncode', models.CharField(max_length=50)),
                ('wantstyle', models.CharField(max_length=50)),
                ('personalInfoAgree', models.BooleanField()),
                ('marketingAgree', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultant.consultant')),
            ],
        ),
    ]
