# Generated by Django 5.0.4 on 2024-05-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('woodworking', models.CharField(max_length=50, null=True)),
                ('woodworkingCount', models.IntegerField(null=True)),
                ('wallpapering', models.CharField(max_length=50, null=True)),
                ('wallpaperingCount', models.IntegerField(null=True)),
                ('floor', models.CharField(max_length=50, null=True)),
                ('floorCount', models.IntegerField(null=True)),
                ('bathroom', models.CharField(max_length=50, null=True)),
                ('bathroomCount', models.IntegerField(null=True)),
                ('sink', models.CharField(max_length=50, null=True)),
                ('sinkCount', models.IntegerField(null=True)),
                ('demolition', models.CharField(max_length=50, null=True)),
                ('demolitionCount', models.IntegerField(null=True)),
                ('basic', models.CharField(max_length=50, null=True)),
                ('basicCount', models.IntegerField(null=True)),
                ('buildingType', models.CharField(max_length=50, null=True)),
                ('interiordate', models.DateField(null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('remainaddress', models.CharField(max_length=150, null=True)),
                ('customername', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('prefertime', models.CharField(max_length=50, null=True)),
                ('promotioncode', models.CharField(max_length=50, null=True)),
                ('wantstyle', models.CharField(max_length=50, null=True)),
                ('personalInfoAgree', models.BooleanField(null=True)),
                ('marketingAgree', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultant.consultant')),
            ],
        ),
    ]
