# Generated by Django 5.0.4 on 2024-05-01 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_remove_consultant_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
