# Generated by Django 5.0.4 on 2024-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0006_alter_consultant_address_alter_consultant_basic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='status',
            field=models.CharField(choices=[('접수', '접수'), ('진행중', '진행중'), ('상담완료', '상담완료'), ('공사진행중', '공사진행중'), ('공사완료', '공사완료'), ('후기작성완료', '후기작성완료')], max_length=20, null=True),
        ),
    ]
